# This workflow checks the Staging Resources CDK project
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Staging Resources CDK App Check

on:
  push:
    branches: [ main ]
    paths:
      - 'release/staging-resources-cdk/**'
  pull_request:
    paths:
      - 'release/staging-resources-cdk/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./release/staging-resources-cdk
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Checkout Data Prepper
      uses: actions/checkout@v2

    - name: Install NPM Dependencies
      run: npm install
    - name: Test
      run: npm run test
    - name: Lint
      run: npm run lint
